jdk: oraclejdk8
language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-21

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

    # Emulator
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-21


  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+


env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - yes | sdkmanager "platforms;android-28"
  -
before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest --warning-mode=all --stacktrace
  - ./gradlew test jacocoTestReport

after_success:
    - bash <(curl -s https://codecov.io/bash)