jdk: oraclejdk8
language: android
dist: trusty

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28

    # Additional components
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services

    # Emulator
  - sys-img-x86-android-28
  - sys-img-armeabi-v7a-android-24


  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-c81a61d9
  - android-sdk-license-.+
  - google-gdk-license-.+

